name: Build CI

on:
  push:
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v2

      # JDKのセットアップ
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Gradleのキャッシュ復元
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # テスト
      - name: Test with Gradle
        run: ./gradlew test --stacktrace
